# All datasets and their paths relative to gtsam/examples/Data
dataset:
    CAB1: 
        is3D:           true
        path:           "ra_datasets/CAB_query_val_phone"
        relin_thresh:   0.01
        start_step:     2
        end_step:       463     # Inclusive
        period:         1
    CAB7000: 
        is3D:           true
        path:           "ra_datasets/CAB7000"
        relin_thresh:   0.02
        start_step:     2
        end_step:       3000    # Inclusive
        period:         25
    sphere2500: 
        is3D:           true
        path:           "sphere2500"
        relin_thresh:   0.05
        start_step:     2
        end_step:       2000    # Inclusive
        period:         25
    w10000: 
        is3D:           false
        path:           "w10000"
        relin_thresh:   0.1
        start_step:     2
        end_step:       10000   # Inclusive
        period:         1
    M3500: 
        is3D:           false
        path:           "ra_datasets/M3500"
        relin_thresh:   0.1
        start_step:     2
        end_step:       3500    # Inclusive
        period:         1
    M3500c: 
        is3D:           false
        path:           "ra_datasets/M3500c"
        relin_thresh:   0.1
        start_step:     2
        end_step:       3500    # Inclusive
        period:         1

# Metadata
metadata:
    scriptdir: "."
    builddir: "../../build"
    headerdir: "../baremetal_tests"
    recompile: true     # True if C++ sources changed
    make_flags: "-j"
    target_binary:
        - testGtsamIncremental
        - testGtsamIncremental3D
        - testGtsamIncremental-ra
        - testGtsamIncremental3D-ra
          # - testGtsamIncremental-vio
          # - testGtsamIncremental3D-vio
        - testGtsamIncremental-treegen
        - testGtsamIncremental3D-treegen
        - testGtsamIncremental-datasetgen
        - testGtsamIncremental3D-datasetgen

# Resource aware
RA:
    # Runs that share the same output_format will use the same dataset run
    output_format: "RA_{dataset}_{'num_threads-{}'.format(num_threads) if not num_threads_file else 'var-threads'}"
    header_format: "RA_{dataset}_{'num_threads-{}'.format(num_threads) if not num_threads_file else 'var-threads'}_steps-{start_step}-{end_step}_period-{period}"
    dataset:    # Comment out the datasets that will be skipped
    # - CAB1
    # - CAB7000
    # - sphere2500
    # - w10000
    # - M3500
    # - M3500c
    params:
        num_threads:        2
        num_threads_file:   ""              # Specify the path to a num threads file or leave empty
        print_dataset:      true            # Turn this off if not generating header
        print_values:       false
        print_pred:         true
        print_traj:         true
        
# Incremental:
Incremental:
    output_format: "incremental_{dataset}"
    header_format: "incremental_{dataset}_steps-{start_step}-{end_step}_period-{period}"
    dataset:    # Comment out the datasets that will be skipped
    # - CAB1
    # - CAB7000
    # - sphere2500
    # - w10000
    # - M3500
    # - M3500c
    params:
        print_dataset:      true            # Turn this off if not generating header
        print_values:       false
        print_pred:         true
        print_traj:         true

# Legacy output directors
Legacy:
    seah_sphere:
        start_step:     2
        end_step:       2000    # Inclusive
        period:         25
        print_values:   false
        output_dir: "incremental_sphere2500_steps-2000_period-25"
        header_dir: "incremental_sphere2500_steps-2000_period-25"
    
